import 'package:freezed_annotation/freezed_annotation.dart';

import 'misskey_drive_folder.dart';
import 'misskey_user.dart';

part 'misskey_drive_file.freezed.dart';
part 'misskey_drive_file.g.dart';

/// A Misskey drive file.
@freezed
@JsonSerializable()
class MisskeyDriveFile with _$MisskeyDriveFile {
  const MisskeyDriveFile({
    required this.id,
    required this.createdAt,
    required this.name,
    required this.type,
    required this.size,
    required this.md5,
    required this.url,
    this.thumbnailUrl,
    this.comment,
    this.folderId,
    this.folder,
    this.userId,
    this.user,
    this.isSensitive,
    this.blurhash,
    this.properties,
    this.isAiGenerated,
  });

  factory MisskeyDriveFile.fromJson(Map<String, dynamic> json) =>
      _$MisskeyDriveFileFromJson(json);

  Map<String, dynamic> toJson() => _$MisskeyDriveFileToJson(this);

  /// The file ID.
  @override
  final String id;

  /// The upload timestamp.
  @override
  final DateTime createdAt;

  /// The file name.
  @override
  final String name;

  /// The MIME type.
  @override
  final String type;

  /// The file size in bytes.
  @override
  final int size;

  /// The MD5 hash of the file.
  @override
  final String md5;

  /// The file URL.
  @override
  final String url;

  /// The thumbnail URL.
  @override
  final String? thumbnailUrl;

  /// The user-provided comment or caption.
  @override
  final String? comment;

  /// The parent folder ID.
  @override
  final String? folderId;

  /// The parent folder.
  @override
  final MisskeyDriveFolder? folder;

  /// The owner user's ID.
  @override
  final String? userId;

  /// The owner user.
  @override
  final MisskeyUser? user;

  /// Whether the file is marked as sensitive.
  @JsonKey(defaultValue: false)
  @override
  final bool? isSensitive;

  /// The blurhash string for image previews.
  @override
  final String? blurhash;

  /// The image properties (width, height, etc.).
  @override
  final MisskeyDriveFileProperties? properties;

  /// Whether this file was generated by AI.
  @JsonKey(defaultValue: false)
  @override
  final bool? isAiGenerated;
}

/// Properties of a drive file (image dimensions, etc.).
@freezed
@JsonSerializable()
class MisskeyDriveFileProperties with _$MisskeyDriveFileProperties {
  const MisskeyDriveFileProperties({
    this.width,
    this.height,
    this.orientation,
    this.avgColor,
  });

  factory MisskeyDriveFileProperties.fromJson(Map<String, dynamic> json) =>
      _$MisskeyDriveFilePropertiesFromJson(json);

  Map<String, dynamic> toJson() => _$MisskeyDriveFilePropertiesToJson(this);

  /// The image width in pixels.
  @override
  final int? width;

  /// The image height in pixels.
  @override
  final int? height;

  /// The EXIF orientation value.
  @override
  final int? orientation;

  /// The average color of the image.
  @override
  final String? avgColor;
}
