import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'getting-started',
    'authentication',
    'pagination',
    'error-handling',
    {
      type: 'category',
      label: 'API Guides',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
  ],
};

export default sidebars;
