import 'dart:async';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:dio/io.dart';
import 'package:misskey_client/misskey_client.dart';

/// A single Misskey server provided by the E2E environment.
///
/// The environment runs more than one Misskey version so that behavioral
/// differences between releases can be verified by the same test bodies.
class MisskeyInstanceEnv {
  const MisskeyInstanceEnv({
    required this.baseUrl,
    required this.adminToken,
    required this.userToken,
  });

  final String baseUrl;
  final String adminToken;
  final String userToken;

  /// The host name, used to label parameterized test cases.
  String get label => Uri.parse(baseUrl).host;
}

/// Connection settings for the local closed-federation E2E environment
/// (`fediverse_e2e`).
///
/// Tests are enabled only when the environment variable `RUN_E2E=1` is set
/// and the `.env.e2e` file generated by `fediverse_e2e/scripts/seed.sh`
/// exists. Otherwise [tryLoad] returns `null` and E2E tests are skipped.
class E2eEnv {
  E2eEnv._({
    required this.misskeyBaseUrl,
    required this.misskeyAdminToken,
    required this.misskeyUserToken,
    required this.misskeyInstances,
    required this.mastodonBaseUrl,
    required this.mastodonAdminToken,
    required this.mastodonUserToken,
    required this.rootCaPath,
  });

  /// Skip reason shown when the E2E environment is not available.
  static const skipReason =
      'E2E environment not available (set RUN_E2E=1 and run '
      'fediverse_e2e: make init)';

  final String misskeyBaseUrl;
  final String misskeyAdminToken;
  final String misskeyUserToken;

  /// Every Misskey server available, starting with the default one.
  ///
  /// Additional servers appear only when the environment defines them, so
  /// version-parameterized tests degrade to the default server alone.
  final List<MisskeyInstanceEnv> misskeyInstances;

  final String mastodonBaseUrl;
  final String mastodonAdminToken;
  final String mastodonUserToken;

  /// Path to the self-signed root CA that the E2E servers use.
  final String rootCaPath;

  /// Loads the E2E environment, or returns `null` when unavailable.
  static E2eEnv? tryLoad() {
    if (Platform.environment['RUN_E2E'] != '1') return null;

    final envPath =
        Platform.environment['E2E_ENV_FILE'] ?? '../fediverse_e2e/.env.e2e';
    final file = File(envPath);
    if (!file.existsSync()) return null;

    final map = <String, String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final index = trimmed.indexOf('=');
      if (index <= 0) continue;
      map[trimmed.substring(0, index)] = trimmed.substring(index + 1);
    }

    // rootCAのパスはホスト絶対パスで書かれているため、
    // 存在しない場合(コンテナ内実行など)は .env.e2e からの相対で解決する
    var caPath = map['E2E_ROOT_CA'] ?? '';
    if (caPath.isEmpty || !File(caPath).existsSync()) {
      caPath = '${file.parent.path}/certs/rootCA.crt';
    }
    if (!File(caPath).existsSync()) return null;

    final misskeyBaseUrl = map['MISSKEY_BASE_URL'];
    final misskeyAdminToken = map['MISSKEY_ADMIN_TOKEN'];
    final misskeyUserToken = map['MISSKEY_USER_TOKEN'];
    final mastodonBaseUrl = map['MASTODON_BASE_URL'];
    final mastodonAdminToken = map['MASTODON_ADMIN_TOKEN'];
    final mastodonUserToken = map['MASTODON_USER_TOKEN'];
    if (misskeyBaseUrl == null ||
        misskeyAdminToken == null ||
        misskeyUserToken == null ||
        mastodonBaseUrl == null ||
        mastodonAdminToken == null ||
        mastodonUserToken == null) {
      return null;
    }

    final misskeyInstances = <MisskeyInstanceEnv>[
      MisskeyInstanceEnv(
        baseUrl: misskeyBaseUrl,
        adminToken: misskeyAdminToken,
        userToken: misskeyUserToken,
      ),
    ];
    // 追加バージョンは環境が提供する場合のみ有効化し、
    // 未導入の環境ではデフォルト1台だけでテストが成立するようにする。
    final extraBaseUrl = map['MISSKEY_2026_7_BASE_URL'];
    final extraAdminToken = map['MISSKEY_2026_7_ADMIN_TOKEN'];
    final extraUserToken = map['MISSKEY_2026_7_USER_TOKEN'];
    if (extraBaseUrl != null &&
        extraAdminToken != null &&
        extraUserToken != null) {
      misskeyInstances.add(
        MisskeyInstanceEnv(
          baseUrl: extraBaseUrl,
          adminToken: extraAdminToken,
          userToken: extraUserToken,
        ),
      );
    }

    return E2eEnv._(
      misskeyBaseUrl: misskeyBaseUrl,
      misskeyAdminToken: misskeyAdminToken,
      misskeyUserToken: misskeyUserToken,
      misskeyInstances: misskeyInstances,
      mastodonBaseUrl: mastodonBaseUrl,
      mastodonAdminToken: mastodonAdminToken,
      mastodonUserToken: mastodonUserToken,
      rootCaPath: caPath,
    );
  }

  /// Creates a dio adapter that trusts the E2E root CA.
  HttpClientAdapter createHttpClientAdapter() => IOHttpClientAdapter(
    createHttpClient: () {
      final context = SecurityContext(withTrustedRoots: true)
        ..setTrustedCertificates(rootCaPath);
      return HttpClient(context: context);
    },
  );

  /// Creates a [MisskeyClient] connected to `misskey.test`.
  ///
  /// Uses the admin token when [admin] is `true`, the regular user token
  /// otherwise.
  MisskeyClient createMisskeyClient({bool admin = false}) =>
      createMisskeyClientFor(misskeyInstances.first, admin: admin);

  /// Creates a [MisskeyClient] connected to [instance].
  MisskeyClient createMisskeyClientFor(
    MisskeyInstanceEnv instance, {
    bool admin = false,
  }) => MisskeyClient(
    config: MisskeyClientConfig(
      baseUrl: Uri.parse(instance.baseUrl),
      timeout: const Duration(seconds: 30),
    ),
    tokenProvider: () => admin ? instance.adminToken : instance.userToken,
    httpClientAdapter: createHttpClientAdapter(),
  );
}

/// Runs [action], retrying while the server reports a rate limit.
///
/// Every suite shares one Misskey instance, so a write can be rejected with
/// HTTP 429 even though the request itself is valid. Honors the
/// server-suggested delay when present.
Future<T> retryOnRateLimit<T>(
  Future<T> Function() action, {
  int maxAttempts = 5,
  Duration initialDelay = const Duration(seconds: 2),
}) async {
  for (var attempt = 1; ; attempt++) {
    try {
      return await action();
    } on MisskeyRateLimitException catch (e) {
      if (attempt >= maxAttempts) rethrow;
      await Future<void>.delayed(e.retryAfter ?? initialDelay * attempt);
    }
  }
}

/// Polls [probe] until it returns non-null, or fails after [timeout].
///
/// 連合配送は非同期のため、到達確認は必ずこれで待つこと。
Future<T> pollUntil<T>(
  Future<T?> Function() probe, {
  Duration timeout = const Duration(seconds: 90),
  Duration interval = const Duration(seconds: 2),
}) async {
  final deadline = DateTime.now().add(timeout);
  Object? lastError;
  while (DateTime.now().isBefore(deadline)) {
    try {
      final result = await probe();
      if (result != null) return result;
    } on Exception catch (e) {
      lastError = e;
    }
    await Future<void>.delayed(interval);
  }
  throw TimeoutException(
    'pollUntil timed out (last error: $lastError)',
    timeout,
  );
}
