import 'dart:async';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:dio/io.dart';
import 'package:misskey_client/misskey_client.dart';

/// Connection settings for the local closed-federation E2E environment
/// (`fediverse_e2e`).
///
/// Tests are enabled only when the environment variable `RUN_E2E=1` is set
/// and the `.env.e2e` file generated by `fediverse_e2e/scripts/seed.sh`
/// exists. Otherwise [tryLoad] returns `null` and E2E tests are skipped.
class E2eEnv {
  E2eEnv._({
    required this.misskeyBaseUrl,
    required this.misskeyAdminToken,
    required this.misskeyUserToken,
    required this.mastodonBaseUrl,
    required this.mastodonAdminToken,
    required this.mastodonUserToken,
    required this.rootCaPath,
  });

  /// Skip reason shown when the E2E environment is not available.
  static const skipReason =
      'E2E environment not available (set RUN_E2E=1 and run '
      'fediverse_e2e: make init)';

  final String misskeyBaseUrl;
  final String misskeyAdminToken;
  final String misskeyUserToken;
  final String mastodonBaseUrl;
  final String mastodonAdminToken;
  final String mastodonUserToken;

  /// Path to the self-signed root CA that the E2E servers use.
  final String rootCaPath;

  /// Loads the E2E environment, or returns `null` when unavailable.
  static E2eEnv? tryLoad() {
    if (Platform.environment['RUN_E2E'] != '1') return null;

    final envPath =
        Platform.environment['E2E_ENV_FILE'] ?? '../fediverse_e2e/.env.e2e';
    final file = File(envPath);
    if (!file.existsSync()) return null;

    final map = <String, String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final index = trimmed.indexOf('=');
      if (index <= 0) continue;
      map[trimmed.substring(0, index)] = trimmed.substring(index + 1);
    }

    // rootCAのパスはホスト絶対パスで書かれているため、
    // 存在しない場合(コンテナ内実行など)は .env.e2e からの相対で解決する
    var caPath = map['E2E_ROOT_CA'] ?? '';
    if (caPath.isEmpty || !File(caPath).existsSync()) {
      caPath = '${file.parent.path}/certs/rootCA.crt';
    }
    if (!File(caPath).existsSync()) return null;

    final misskeyBaseUrl = map['MISSKEY_BASE_URL'];
    final misskeyAdminToken = map['MISSKEY_ADMIN_TOKEN'];
    final misskeyUserToken = map['MISSKEY_USER_TOKEN'];
    final mastodonBaseUrl = map['MASTODON_BASE_URL'];
    final mastodonAdminToken = map['MASTODON_ADMIN_TOKEN'];
    final mastodonUserToken = map['MASTODON_USER_TOKEN'];
    if (misskeyBaseUrl == null ||
        misskeyAdminToken == null ||
        misskeyUserToken == null ||
        mastodonBaseUrl == null ||
        mastodonAdminToken == null ||
        mastodonUserToken == null) {
      return null;
    }

    return E2eEnv._(
      misskeyBaseUrl: misskeyBaseUrl,
      misskeyAdminToken: misskeyAdminToken,
      misskeyUserToken: misskeyUserToken,
      mastodonBaseUrl: mastodonBaseUrl,
      mastodonAdminToken: mastodonAdminToken,
      mastodonUserToken: mastodonUserToken,
      rootCaPath: caPath,
    );
  }

  /// Creates a dio adapter that trusts the E2E root CA.
  HttpClientAdapter createHttpClientAdapter() => IOHttpClientAdapter(
    createHttpClient: () {
      final context = SecurityContext(withTrustedRoots: true)
        ..setTrustedCertificates(rootCaPath);
      return HttpClient(context: context);
    },
  );

  /// Creates a [MisskeyClient] connected to `misskey.test`.
  ///
  /// Uses the admin token when [admin] is `true`, the regular user token
  /// otherwise.
  MisskeyClient createMisskeyClient({bool admin = false}) => MisskeyClient(
    config: MisskeyClientConfig(
      baseUrl: Uri.parse(misskeyBaseUrl),
      timeout: const Duration(seconds: 30),
    ),
    tokenProvider: () => admin ? misskeyAdminToken : misskeyUserToken,
    httpClientAdapter: createHttpClientAdapter(),
  );
}

/// Polls [probe] until it returns non-null, or fails after [timeout].
///
/// 連合配送は非同期のため、到達確認は必ずこれで待つこと。
Future<T> pollUntil<T>(
  Future<T?> Function() probe, {
  Duration timeout = const Duration(seconds: 90),
  Duration interval = const Duration(seconds: 2),
}) async {
  final deadline = DateTime.now().add(timeout);
  Object? lastError;
  while (DateTime.now().isBefore(deadline)) {
    try {
      final result = await probe();
      if (result != null) return result;
    } on Exception catch (e) {
      lastError = e;
    }
    await Future<void>.delayed(interval);
  }
  throw TimeoutException(
    'pollUntil timed out (last error: $lastError)',
    timeout,
  );
}
